name: grocery_app
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.12.2


dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.2.1
  lottie: ^3.3.2
  device_preview: ^1.2.0
  iconsax_flutter: ^1.0.1
  provider: ^6.1.2
  shared_preferences: ^2.5.3
  image_picker: ^1.2.0





  intl: any
  go_router: ^18.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "assets/images/app_icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon_foreground.png"                                       


flutter:
  uses-material-design: true
  fonts:
    - family: poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: poppinsbold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf




  assets:
    - assets/images/
    - assets/lottie/Loading Dots Blue.json





