// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCL1IPhEvNY73dvY8UbEybEKO2LfRZItrQ',
    appId: '1:129191850915:android:2f87e91566eddafda12016',
    messagingSenderId: '129191850915',
    projectId: 'grocery-app-248c0',
    storageBucket: 'grocery-app-248c0.firebasestorage.app',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAky6dJUlcOCSPNbnGl0soq4-GVi-GLyyM',
    appId: '1:129191850915:web:c736ed485ba75644a12016',
    messagingSenderId: '129191850915',
    projectId: 'grocery-app-248c0',
    authDomain: 'grocery-app-248c0.firebaseapp.com',
    storageBucket: 'grocery-app-248c0.firebasestorage.app',
    measurementId: 'G-9JP60HWK22',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAky6dJUlcOCSPNbnGl0soq4-GVi-GLyyM',
    appId: '1:129191850915:web:f4271b64f7297c6ba12016',
    messagingSenderId: '129191850915',
    projectId: 'grocery-app-248c0',
    authDomain: 'grocery-app-248c0.firebaseapp.com',
    storageBucket: 'grocery-app-248c0.firebasestorage.app',
    measurementId: 'G-WZCY148XSW',
  );
}
